---
 
    deployment:
     
     tasks:
     
     - export DEPLOYPATH=/home/haibersa/api.haibersama.com
     - /bin/cp .htaccess $DEPLOYPATH
     - /bin/cp .env $DEPLOYPATH
     - /bin/cp -r * $DEPLOYPATH
